### ISSUE TITLE
pls suppor for TF pb format

### ISSUE THREAD

**Issue by dsp6414** [kuroko1t/nne#9]
pls suppor for TF pb format

**Comment by kuroko1t** [comment]
In the process of converting to a model for tflite, nne outputting a protobuf format file.
If you comment out the following lines, the protobuf format file will not be deleted.
https://github.com/kuroko1t/nne/blob/f8f675dd9646bf8d03af8091ea529bbec6ffc071/nne/tflite.py#L79
